FROM node:16.15

RUN npm install -g pnpm@7.1.0

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY index.html .eslintrc.js .prettierrc.js apollo.config.js vite.config.ts tsconfig.json ./